# Debug
# Info
# Warning
# Error
# Critical

# 2023-05-02 19:00:00, 000 : ERROR: <testcasename>: Critical error in placing an order on step
# 51. Cannot continue the testing.

# import logging
#
#
# def test_logging():
#     log = logging.getLogger(__name__)
#     filehandler = logging.FileHandler("logs.log")
#     log.addHandler(filehandler)
#     set_format = logging.Formatter("%(asctime)s : %(levelname)s : %(name)s : %(message)s")
#     filehandler.setFormatter(set_format)
#     log.setLevel(logging.ERROR)
#
#     log.warning("Warning statement")
#     log.debug("Debug statement")
#     log.info("Info statement")
#     log.info("Second info statement")
#     log.debug("Second debug statement")
#     log.debug("Debug statement")
#     log.info("Info statement")
#     log.error("Error statement")
#     log.critical("Critical statement")


